# Generated by Django 6.1 on 2026-09-26 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del grupo')),
                ('can_access_inventory', models.BooleanField(default=False, verbose_name='Inventario')),
                ('can_access_sales', models.BooleanField(default=False, verbose_name='Ventas (salida)')),
                ('can_access_purchases', models.BooleanField(default=False, verbose_name='Compras (entrada)')),
                ('can_access_users', models.BooleanField(default=False, verbose_name='Usuarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='Nombre de usuario')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_platform_admin', models.BooleanField(default=False, verbose_name='Administrador de plataforma')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.company', verbose_name='Empresa')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.group', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_group_name_per_company'),
        ),
    ]
