# Generated by Django 6.1 on 2026-08-29 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='Nombre de usuario')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellidos')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('employee', 'Empleado')], default='employee', max_length=20, verbose_name='Rol de usuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado de usuario')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Equipo técnico')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de union')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Última sesión')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='companies.branch', verbose_name='Sucursal (gerente/empleado)')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='companies.company', verbose_name='Empresa (solo administrador)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario personalizado',
                'verbose_name_plural': 'Usuarios personalizados',
            },
        ),
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_inventory', models.BooleanField(default=False, verbose_name='Gestionar inventario')),
                ('can_manage_sales', models.BooleanField(default=False, verbose_name='Gestionar ventas')),
                ('can_manage_employees', models.BooleanField(default=False, verbose_name='Gestionar empleados')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Ver reportes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_permissions', to='companies.branch', verbose_name='Sucursal')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de empleado',
                'verbose_name_plural': 'Permisos de empleados',
            },
        ),
    ]
