# Generated by Django 6.1 on 2026-08-20 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_inventory', models.BooleanField(default=False, verbose_name='Gestionar inventario')),
                ('can_manage_sales', models.BooleanField(default=False, verbose_name='Gestionar ventas')),
                ('can_manage_employees', models.BooleanField(default=False, verbose_name='Gestionar empleados')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Ver reportes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_permissions', to='companies.company', verbose_name='Empresa')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de empleado',
                'verbose_name_plural': 'Permisos de empleados',
            },
        ),
    ]
