# Generated by Django 6.1 on 2026-09-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la plantilla')),
                ('can_access_inventory', models.BooleanField(default=False, verbose_name='Inventario')),
                ('can_access_sales', models.BooleanField(default=False, verbose_name='Ventas (salida)')),
                ('can_access_purchases', models.BooleanField(default=False, verbose_name='Compras (entrada)')),
                ('can_access_users', models.BooleanField(default=False, verbose_name='Usuarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Plantilla de grupo',
                'verbose_name_plural': 'Plantillas de grupo',
            },
        ),
    ]
