# Generated by Django 6.1 on 2026-08-28 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_company_employeepermission'),
        ('companies', '0005_remove_company_address_remove_company_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepermission',
            name='company',
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='companies.branch', verbose_name='Sucursal (gerente/empleado)'),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_permissions', to='companies.branch', verbose_name='Sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='companies.company', verbose_name='Empresa (solo administrador)'),
        ),
    ]
