# Generated by Django 6.1 on 2026-09-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_add_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptemplate',
            name='can_manage_inventory',
            field=models.BooleanField(default=False, verbose_name='Administrar inventario (crear/editar productos)'),
        ),
        migrations.AlterField(
            model_name='grouptemplate',
            name='can_access_inventory',
            field=models.BooleanField(default=False, verbose_name='Inventario (ver productos)'),
        ),
    ]
