# Generated by Django 6.1 on 2026-08-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='branch',
            field=models.CharField(default=1, verbose_name='Sucursal'),
            preserve_default=False,
        ),
    ]
