# Generated by Django 6.1 on 2026-08-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='branch',
            field=models.BooleanField(default=False, verbose_name='Sucursal'),
        ),
    ]
