# Generated by Django 6.1 on 2026-08-28 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='branch',
        ),
    ]
