# Generated by Django 6.1 on 2026-08-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_company_address_remove_company_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
