# Generated by Django 6.1 on 2026-09-02 23:21

import django.db.models.deletion
from django.db import migrations, models


def poblar_branch_stock(apps, schema_editor):
    # Mueve el stock actual (que estaba en ProductModel) a BranchStock.
    # El valor viejo va a la PRIMERA sucursal de la empresa; el resto arranca en 0.
    Product = apps.get_model('inventory', 'ProductModel')
    BranchStock = apps.get_model('inventory', 'BranchStock')

    for p in Product.objects.all():
        for i, branch in enumerate(p.company.branches.all()):
            BranchStock.objects.create(
                product=p,
                branch=branch,
                stock=p.stock if i == 0 else 0,
            )


def revertir(apps, schema_editor):
    # Al revertir, se devuelve a ProductModel.stock el valor de la primera sucursal.
    Product = apps.get_model('inventory', 'ProductModel')
    BranchStock = apps.get_model('inventory', 'BranchStock')

    for p in Product.objects.all():
        bs = BranchStock.objects.filter(product=p).order_by('branch_id').first()
        if bs:
            p.stock = bs.stock
            p.save(update_fields=['stock'])


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        # 1) Se crea la tabla nueva.
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo en esta sucursal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='companies.branch', verbose_name='Sucursal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='inventory.productmodel', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Stock por sucursal',
                'verbose_name_plural': 'Stocks por sucursal',
                'constraints': [models.UniqueConstraint(fields=('product', 'branch'), name='unique_product_per_branch')],
            },
        ),
        # 2) Se copian los datos ANTES de borrar la columna vieja.
        migrations.RunPython(poblar_branch_stock, revertir),
        # 3) Recien ahora se elimina ProductModel.stock.
        migrations.RemoveField(
            model_name='productmodel',
            name='stock',
        ),
    ]
