# Generated by Django 6.1 on 2026-09-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_category_unique_category_name_per_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='reason',
            field=models.CharField(blank=True, choices=[('compra', 'Compra'), ('venta', 'Venta'), ('ajuste', 'Ajuste'), ('merma', 'Merma'), ('devolucion', 'Devolución')], max_length=20, verbose_name='Motivo'),
        ),
    ]
