# Generated by Django 6.1 on 2026-09-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_movement_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='reason',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('ajuste', 'Ajuste'), ('merma', 'Merma'), ('devolucion', 'Devolución')], max_length=20, verbose_name='Motivo'),
        ),
    ]
