# Generated by Django 6.1 on 2026-09-26 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_movement_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio de costo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5)], verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio de venta'),
        ),
    ]
