# Generated by Django 6.1 on 2026-09-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario'),
        ),
    ]
