# Generated by Django 6.1 on 2026-09-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_backfill_movement_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Lote'),
        ),
    ]
